export enum EPermission {
  DEFAULT = 'DEFAULT',

  ADD_USER = 'ADD_USER',
  UPDATE_USER = 'UPDATE_USER',
  ADMIN_UPDATE_USER = 'ADMIN_UPDATE_USER',
  FIND_USER = 'FIND_USER',
  GET_USER = 'GET_USER',
  DELETE_USER = 'DELETE_USER',
  LOCK_USER = 'LOCK_USER',
  UNLOCK_USER = 'UNLOCK_USER',

  DATA_RECOVERY = 'DATA_RECOVERY',

  ADD_ROLE = 'ADD_ROLE',
  UPDATE_ROLE = 'UPDATE_ROLE',
  FIND_ROLE = 'FIND_ROLE',
  GET_ROLE = 'GET_ROLE',
  DELETE_ROLE = 'DELETE_ROLE',

  ADD_HOUSE = 'ADD_HOUSE',
  UPDATE_HOUSE = 'UPDATE_HOUSE',
  FIND_HOUSE = 'FIND_HOUSE',
  GET_HOUSE = 'GET_HOUSE',
  DELETE_HOUSE = 'DELETE_HOUSE',

  ADD_SAVED_ROOM = 'ADD_SAVED_ROOM',
  DELETE_SAVED_ROOM = 'DELETE_SAVED_ROOM',
  FIND_SAVED_ROOM = 'FIND_SAVED_ROOM',

  GET_PROFILE = 'GET_PROFILE',
  FIND_REVIEW = 'FIND_REVIEW',
  ADD_REVIEW = 'ADD_REVIEW',
  FIND_CONTRACT = 'FIND_CONTRACT',
  ADD_CONTRACT = 'ADD_CONTRACT',
  GET_CONTRACT = 'GET_CONTRACT',
  UPDATE_CONTRACT = 'UPDATE_CONTRACT',
  SIGN_CONTRACT = 'SIGN_CONTRACT',
  CONFIRM_PAYMENT = 'CONFIRM_PAYMENT',
  OCR_CCCD = 'OCR_CCCD',
}
